// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtOri-v2mnO4aaDJ3JVc32ltkBYMJ33RA',
    appId: '1:180167696647:web:32225f1ed9337723e6a5a2',
    messagingSenderId: '180167696647',
    projectId: 'dineout-984f0',
    authDomain: 'dineout-984f0.firebaseapp.com',
    storageBucket: 'dineout-984f0.firebasestorage.app',
    measurementId: 'G-ETQ2F4CVBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpvIe52H3dSWSgSAf8jQQEh7Sh-kAl5Bg',
    appId: '1:180167696647:android:3baa00c62bcd7cbfe6a5a2',
    messagingSenderId: '180167696647',
    projectId: 'dineout-984f0',
    storageBucket: 'dineout-984f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCVAYzKaFzfBtd5jamuO3cFjXxkxKtz2I',
    appId: '1:180167696647:ios:7344774c388e96fee6a5a2',
    messagingSenderId: '180167696647',
    projectId: 'dineout-984f0',
    storageBucket: 'dineout-984f0.firebasestorage.app',
    iosBundleId: 'com.dineout.dineout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your-ios-api-key',
    appId: 'your-ios-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
    iosBundleId: 'com.dineout.dineout',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'your-web-api-key',
    appId: 'your-web-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'your-project-id',
    authDomain: 'your-project-id.firebaseapp.com',
    storageBucket: 'your-project-id.appspot.com',
  );
}